[project]
name = "ml-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.2"
dependencies = [
    "jax>=0.7.2",
    "jupyter>=1.1.1",
    "numpyro>=0.19.0",
    "scikit-learn>=1.7.2",
    "torch>=2.8.0",
    "unidecode>=1.4.0",
]
